backend:
    name: git-gateway
    branch: master

media_folder: static/img
public_folder: /img
site_url: https://ianlamb.com

collections:
    - name: blog
      label: 'Blog'
      folder: content/blog
      create: true
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Path', name: 'path', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
    - name: projects
      label: 'Projects'
      folder: content/projects
      create: true
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
                label: 'Path',
                name: 'path',
                widget: 'string',
                default: '/projects/<project-slug>',
            }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Source (GitHub)', name: 'source', widget: 'string' }
          - { label: 'URL (Live Site)', name: 'url', widget: 'string' }
          - { label: 'Image', name: 'image', widget: 'image' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - {
                label: 'Featured',
                name: 'featured',
                widget: 'boolean',
                default: false,
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }
    - name: pages
      label: 'Pages'
      files:
          - name: home
            label: 'Home'
            file: content/pages/home.yml
            fields:
                - { label: 'Title', name: title, widget: string }
                - { label: 'Intro', name: intro, widget: string }
                - name: social
                  label: 'Social Links'
                  widget: list
                  fields:
                      - { label: 'Label', name: label, widget: string }
                      - { label: 'URL', name: url, widget: string }
                - name: quotes
                  label: 'Quotes'
                  widget: list
                  fields:
                      - { label: 'Quote', name: quote, widget: string }
                      - { label: 'Author', name: author, widget: string }
                - name: travel
                  label: 'Travel Stats'
                  widget: list
                  fields:
                      - { label: 'Label', name: label, widget: string }
                      - {
                            label: 'Value',
                            name: value,
                            widget: number,
                            value_type: int,
                        }
                      - {
                            label: 'Max Value',
                            name: max,
                            widget: number,
                            value_type: int,
                        }
